typography_spectrum: 0.14757274300791323
color:
  brandStrength: 0.8593731278087944
  lightness: 0.2967260596342385
  saturation: 0.1415209888946265
  rhythmicContrast: 0.5071162842214108
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
layout_spectrum: 0.7736632900778204
author:
  name: Oliver Wüseke
  email: ''
name: The HuB
navigation:
  - name: Venturing into the unknown…
    id: 24a4cd41-98fa-452b-ad08-fc9d219c1b0d
    type: content
title: on fire
description: neuronal networks in human cerebral organoids
